---
title: "Imputation SIPP"
author: "Chong Li"
date: "4/25/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse,tidycensus,readxl,patchwork)
library(reshape2)
library(mice)
require("data.table")
require("bit64")

census_api_key("e0ff7586a0faf3bf1819178c1392ba6fa3df7ad9")
```

```{r}
frs_individuals = read.csv("./data/cleaned_data/acs_individuals.csv")
frs_df = read.csv("./data/cleaned_data/frs_inputs_3.csv")
```

```{r}
# let the outcome Y be household income
# let the covariates takeN from FRS to be 
# 1. person reference/state 2. age 3. class of work 4. education level 5. marital status 6. relationship 7. race. 8. gender. 9. work hours 10. personal income 11. Nativity 

acs_model = frs_individuals %>% 
  select(SERIALNO, ST, AGEP, COW, SCHL, MSP, RELSHIPP, RAC1P, SEX, WKHP, PINCP, NATIVITY)
```

```{r}
acs_model %>% head()
```

```{r}
# The following code is an example of reading the pipe-delimited Survey of Income and Program Participation (SIPP) 
# 	data into an R dataframe in preparation for analysis. Specifically, this code loads in both the primary data file 
#   and the calendar-year replicate weights file (as opposed to the longitudinal replicate weights). These files are 
#   separate downloads on the SIPP website.
# SIPP data are in person-month format, meaning each record represents one month for a specific person.
#   Unique persons are identified using SSUID+PNUM. Unique households are identified using SSUID+ERESIDENCEID. For 
#   additional guidance on using SIPP data, please see the SIPP Users' Guide at <https://www.census.gov/programs-surveys/sipp/guidance/users-guide.html>
# This code was written in R 4.1.0, and requires the "data.table", "dplyr", and "bit64" packages. 
# Note the 'select' statement in the first use of fread(). Most machines do not have enough memory to read
# 	the entire SIPP file into memory. Use a 'select' statement to read in only the columns you are interested in using. 
#   If you still encounter an out-of-memory error, you must select less columns or less observations.
# Run this code from the same directory as the extracted data.
# This code was written by Adam Smith. Please contact census.sipp@census.gov if you have any questions.

#Load the "data.table", "dplyr", and "bit64" libraries

#Read in the Primary Data file. Choose only the variables you want to read in in order to save on memory.
#This code assumes that your working directory is the same directory as the data.
pu <- fread("./data/pu2020.csv", sep = "|", select = c(
  
  #Common case identification variables
	'SSUID','PNUM','MONTHCODE','ERESIDENCEID','ERELRPE','SPANEL','SWAVE',
	
	#The base weight
	'WPFINWGT',
	
	#Common demographics variables, including age at time of interview (TAGE)
	#	and monthly age during the reference period (TAGE_EHC)
	'ESEX','TAGE','ERACE','EORIGIN','EEDUC',
	
	#Example additional variables for analysis
	'TPTOTINC'))

#Make sure all the column names are upper-case
names(pu) <- toupper(names(pu))

#Preview the data
head(pu, 20)
```

```{r}
# 1. SSUID/PNUM/MONTHCODE and TEHC_ST 2. TAGE 4. EEDUC 5. EMS_EHC 6. ERELRPE 7. ERACE 8. ESEX 9. TMWKHRS 10. TPTOTINC 11. EBORNUS 12. TIMSTAT

pu <- fread("./data/pu2020.csv", sep = "|", select = c(
  
  #Common case identification variables
	'SSUID','PNUM','MONTHCODE','TEHC_ST','TAGE','EEDUC','EMS_EHC', 'ERLRPE', 'ERACE', 'ESEX', 'TMWKHRS', 'TPTOTINC', 'EBORNUS',"ECITIZEN","ENATCIT",'TIMSTAT'))
```

```{r}
sipp_immi = pu %>% 
  filter(TEHC_ST == 34) %>% 
  filter(MONTHCODE == 10) %>% 
  filter(TAGE > 17)
```

```{r}
sipp_immi %>% 
  mutate(
    id = paste0(SSUID,"_",PNUM)
  ) %>% 
  relocate(id,everything()) %>% 
  select(-c(SSUID,PNUM,MONTHCODE)) %>% 
  filter(EBORNUS != 1)
```

