#=============================================================================#
#  School & Summer Meals Module – 2021  
#=============================================================================#
#Note: This is a new federal code as of 2021. From 2017-2021, we used a version of this code but used state-specific versions of it. We have since streamlined teh code and adjusted the frs_locations tab, and added additional relevant variables to the user interface, to an extent that this code is now fully generic and can be applied across states.
#
# NOTE FOR FUTURE USE: 
# This code began as state-specific, but it is getting general enough that it may merit removal from here and consideration as a federal/generic code. The only state-level decision remaining is the treatment of the in-code cep_participation variable and the cep input variable, and where we want to build in state variation, that could be included in either the frs_locations tab or the fsp_assets module.

# Inputs referenced in this module or outputs from other module needed for this module:
#
# INPUTS FROM USER INTERFACE
# 	child#_age
# 	nsbp 
# 	frpl 
# 	sfsp 
#	prek
# 	cacfp = 1; #We could add this as an input, but so far have not; absent a public afterschool program, CACFP benefits are difficult to model. While for a public afterschool program, participation could be modeled as reducing food costs from the free provision of meals to participating children, it is difficult to determine whether these costs are included or not in the market rates of child care, and whether savings in child care generated by CCDF reductions already incorporate savings from free or low-cost provision of school meals. It is used below to determine whether childred in the family being modeled receives free suppers when participating in afterschool programs. This is offered to Pittsburgh children, as indicated at https://pittsburghpa.gov/citiparks/grubup. 
#	child#_foster_status #SS 10/7: added to indicate whether a child is a foster child or not. Foster children are categorically eligible for free meals. see https://www.fns.usda.gov/cn/verification-and-reporting-foster-children. 	
#	weekend_meals_alt		#this is a policy modeling option. "Policy change: Model children receiving meals during weekends during the school year." This was proposed in Hunger Free NJ's 2019 report: https://njfoodforthought.org/wp-content/uploads/sites/11/2019/08/HFNJ_AfterschoolMeals_Report_2019.pdf.  
#	IMMIGRANTS: child immigration status is not assessed when assessing eligibility for school meal programs and was exempted from 1996 welfare restrictions on immigrants.https://www.law.cornell.edu/uscode/text/8/1615.  immigration checks not necessary for school meals calculation. HOWEVER migrant children are categorically eligible for free meals: https://www.fns.usda.gov/categorical-eligibility-free-lunches-and-breakfasts-migrant-children. We have not yet programmed in rules or benefits related to migrant children.
#	expanding_cep_eligiblity_alt 		#This is a policy modeling option that will ask: "Policy option: Model all children to be eligible for school meals through Community Eligibility Provision." 
#
# INPUTS FROM NCCP_SIMULATOR.PHP MYSQL PULLS
#	schooldays
#	summerdays
#
# INPUTS FROM FRS.PM
# 	fpl 
#
# OUTPUTS FROM INTEREST
# 	interest_m 
#
# OUTPUTS FROM PARENT EARNINGS
# 	earnings
#
# OUTPUTS FROM SSI
# 	ssi_recd_mnth
#
# OUTPUTS FROM TANF
# 	tanf_recd_m
# 	tanf_recd
# 	child_support_recd_m
#
# FROM FSP
# 	fsp_recd
#
# FROM CHILD_CARE
# 	prek_age_min 	
# 	prek_age_max 	
#	
# FROM FLI_TDI
#	fli_plus_tdi_recd 
#
#=============================================================================#

sub schoolsummermeals
{
    my $self = shift;
    my $in = $self->{'in'};
    my $out = $self->{'out'};

	# outputs created
	#NOTE: The input screens (on step 7) will ask whether the parent is sending their children to a school that takes up the community eligibility provision or Provision 2 of federal school meal legislation in counties where there are schools that have taken up this provision. The Commnuity Eligibility Provision (CEP)  allows schools or school districts to provide free breakfasts and lunches to all students, regardless of income or SNAP participation. Schools or districts are eligible to participate in this program if 40% or more of students are calculated as eligible for participate. Incentives for schools participating in this program include lower administrative costs (no one needs to check student income or confirm eligibility in the lunch line) and a higher federal reimbursement rate for meals (at 1.6 times the normal reimbursement rate). Schools still pay the difference between the total federal reimbursements and the costs of providing school meals, but schools also determine the costs of meals students receive. 

	#Full price meal costs:
	our $elem_lunch_paid = 2.48; #This is the average full-price lunch cost for elementary school students in 2016-2017, based on a 2018 School Nutrition Association report (widely respected), nationally, pre-covid. Normally we'd try to identify the cost per school district or average cost per state or locality, but during COVID all these lunches are free, at least through the end of the 2020-2021 school year. So any price here would be a bit of an abstraction. School lunch and breakfast prices don't vary much, beyond whether schools provide meals for free or not. See https://schoolnutrition.org/aboutschoolmeals/schoolmealtrendsstats/. 
	our $elem_bkfst_paid = 1.46; #This is the average full-price breakfast cost for elementary school students nationally as of 2016-2017. 
	our $ms_lunch_paid = 2.68; #This is the average full-price breakfast cost for middle school students nationally as of 2016-2017, pre-covid. 
	our $ms_bkfst_paid = 1.53; #This is the average full-price breakfast cost for middle school students nationally as of 2016-2017, pre-covid. 
	our $hs_lunch_paid = 2.74; #Same as above, for HS students.
	our $hs_bkfst_paid =1.55;  #Same as above, for HS students.

	#Reduced price meal costs:
	our $elem_lunch_red = 0.4; # In general, reduced-price lunch is $0.40. Previous FRS codes estimated the prices of school lunch at the town / school district level, but there is so little variation there, it's likely not worth the trouble.
	our $elem_bkfst_red = 0.3; # In general, reduced-price breakfast is $0.30. Previous FRS codes estimated the prices of school lunch at the town / school district level, but there is so little variation there, it's likely not worth the trouble. The main difference is whether schools offer reduced price breakfast or not, but users are indicating in the input pages of the MTRC whether their children are participating in this program. Conceivably, we could ask exactly which children receive these benefits (since they may go to different schools), but it seems probable that if one child attends a school with reduced price meals, the other will as well. While we have done this data dig for NH, the process was onerous enough that it does not seem appropriate to ask for these fields to be updated beyond adjusting the standard prices set at the federal level.
	our $ms_lunch_red = 0.4;
	our $ms_bkfst_red = 0.3;
	our $hs_lunch_red = 0.4;
	our $hs_bkfst_red = 0.3;

	our $summer_pebt_amt = 375; #The amount determined in 2020 by the federal government to be equivalent to the federal subsidy for providing summer meals to children. For participating states, this amount is available to all children regardless of age as a replacement for summer meal programs as part of the Pandemic EBT program, pending the submission of state plans.
	
	our $elem_cep_lunch	= 0; #whether there is an elementary school in the district that offers free school lunch to all studets.
	our $elem_cep_bkfst	= 0; #whether there is an elementary school in the district that offers free school breakfast to all studets.
	our $ms_cep_lunch = 0; #whether there is an middle school in the district that offers free school lunch to all studets.
	our $ms_cep_bkfst = 0; #whether there is an middle school in the district that offers free school breakfast to all studets.
	our $hs_cep_lunch = 0; #whether there is an high school in the district that offers free school lunch to all studets.
	our $hs_cep_bkfst = 0; #whether there is an high school in the district that offers free school breakfast to all studets.
	
 	our $permealcost = 0;		#per meal cost for each child
	our $child1_bkfst_red = 0;	#reduction in child food costs due to free breakfast 
	our $child2_bkfst_red = 0;	#reduction in child food costs due to free breakfast 
	our $child3_bkfst_red = 0;	#reduction in child food costs due to free breakfast 
	our $child4_bkfst_red = 0;	#reduction in child food costs due to free breakfast 
	our $child5_bkfst_red = 0;	#reduction in child food costs due to free breakfast 
	our $child1_lunch_red = 0;	#reduction in child food costs due to free lunch 
	our $child2_lunch_red = 0;	#reduction in child food costs due to free lunch 
	our $child3_lunch_red = 0;	#reduction in child food costs due to free lunch 
	our $child4_lunch_red = 0;	#reduction in child food costs due to free lunch 
	our $child5_lunch_red = 0;	#reduction in child food costs due to free lunch 
	our $child1_supper_recd = 0;	# reduc. in child food cost due to free afterschool snack/supper 
	our $child2_supper_recd = 0;	# reduc. in child food cost due to free afterschool snack/supper 
	our $child3_supper_recd = 0;	# reduc. in child food cost due to free afterschool snack/supper 
	our $child4_supper_recd = 0;	# reduc. in child food cost due to free afterschool snack/supper 
	our $child5_supper_recd = 0;	# reduc. in child food cost due to free afterschool snack/supper 
	our $child1_sfsp_red = 0;	#reduction in child food costs due to summer meals 
	our $child2_sfsp_red = 0;	#reduction in child food costs due to summer meals 
	our $child3_sfsp_red = 0;	#reduction in child food costs due to summer meals 
	our $child4_sfsp_red = 0;	#reduction in child food costs due to summer meals 
	our $child5_sfsp_red = 0;	#reduction in child food costs due to summer meals 
	our $bkfst_paid_price = 0;
	our $bkfst_red_price = 0;
	our $cep_participation_bkfst = 0;
	our $lunch_paid_price = 0;
	our $lunch_red_price = 0;
	our $cep_participation_lunch = 0;
	our $child_foodcost_red_total = 0; #Total reduction in children’s food costs due to meal programs
	our $schoolmeals_inc_m = 0;	#countable income to assess eligibility for free lunch
	our $schoolmeals_inc = 0;	#annual countable income to assess eligibility
	our $child1_foodcost_red = 0;
	our $child2_foodcost_red = 0;
	our $child3_foodcost_red = 0;
	our $child4_foodcost_red = 0;
	our $child5_foodcost_red = 0;
	our $child1_foodcost_m = 0;
	our $child2_foodcost_m = 0;
	our $child3_foodcost_m = 0;
	our $child4_foodcost_m = 0;
	our $child5_foodcost_m = 0;	
	our $sfsp_program = 0;
	our $schooldays = 0;	
	our $summerdays = 0;
	our $cep_participation = 0;
	our $summerweeks = 0;
	our $cep_takeup = 0; 
	our $debug1 = 0;
	our $debug2 = 0;
	our $debug3 = 0;
	our $debug4 = 0;
	our $debug5 = 0;
	
	#We can also run the income test for free lunch eligibility at this point, since that will be true across all children.  Identical to SSI income determinations, but SSI assistance is included. Reportable Income (https://www.ssa.gov/OP_Home/cfr20/416/416-app-k.htm) includes earnings, SSI, cash assistance, child support, and any other money available to pay for children’s meals. SNAP value is not counted. 

	#Retrieving schooldays and summerdays, 
	my $sql = "SELECT DISTINCT schooldays FROM FRS_Locations WHERE state = ? AND year = ? AND id = ?";
	my $stmt = $dbh->prepare($sql) ||
		&fatalError("Unable to prepare $sql: $DBI::errstr");
	my $result = $stmt->execute($in->{'state'}, $in->{'year'}, $in->{'residence'}) ||
		&fatalError("Unable to execute $sql: $DBI::errstr");
	$schooldays = $stmt->fetchrow();

	my $sql = "SELECT DISTINCT summerdays FROM FRS_Locations WHERE state = ? AND year = ? AND id = ?";
	my $stmt = $dbh->prepare($sql) ||
		&fatalError("Unable to prepare $sql: $DBI::errstr");
	my $result = $stmt->execute($in->{'state'}, $in->{'year'}, $in->{'residence'}) ||
		&fatalError("Unable to execute $sql: $DBI::errstr");
	$summerdays = $stmt->fetchrow();
	
	my $sql = "SELECT DISTINCT cep_particpation FROM FRS_Locations WHERE state = ? AND year = ? AND id = ?"; #Note there is a typo in the SQL file for this column - "cep_particpation" instead of "cep_participation". Typo is corrected for sanity below but it should also eventually reflect the correct spelling in the MySQL database.
	my $stmt = $dbh->prepare($sql) ||
		&fatalError("Unable to prepare $sql: $DBI::errstr");
	my $result = $stmt->execute($in->{'state'}, $in->{'year'}, $in->{'residence'}) ||
		&fatalError("Unable to execute $sql: $DBI::errstr");
	$cep_participation = $stmt->fetchrow();

	#add policy modeling option to allow children to receive meals on weekends/school holidays
	if ($in->{'weekend_meals_alt'} == 1) {
		my $sql = "SELECT DISTINCT summerweeks FROM FRS_Locations WHERE state = ? && year = ? && id = ?";
		my $stmt = $dbh->prepare($sql) ||
			&fatalError("Unable to prepare $sql: $DBI::errstr");
		$stmt->execute($in->{'state'}, $in->{'year'}, $in->{'residence'}) ||
			&fatalError("Unable to execute $sql: $DBI::errstr");
		$summerweeks = $stmt->fetchrow();

		
		$schooldays = round((52 - $summerweeks) * 7); #While we could add 2 more days for weekends based on the number of schooldays in the SQL table, that formula wouldn't incorporate school holidays. This formula backs into the provision of meals during holidays and weekends during the school year by finding the number of weeks during the school year and then multiplying that by the number of days in a week.
	}		
	#We now check for whether we need to "fix" the CEP input variable when being used in the testing site, which does not check for CEP availability in a county. The UI does check for this. So when using the UI, cep_takeup will always be equal to the cep input variable. But it's possible using the testing interface that that cep input variable will be 1 in a county that 
	if ($cep_participation == 0 && $in->{'cep'} == 1) {
		$cep_takeup = 0;
	} elsif ($in->{'expanding_cep_eligiblity_alt'} == 1) {
		$cep_takeup = 1;
	} else {
		$cep_takeup = $in->{'cep'};
	}
	
	if ($in->{'child_number'} == 0) {
		$child_foodcost_red_total = 0;
	} else {
		if ($in->{'nsbp'}==1 || $in->{'frpl'} == 1 || $in->{'fsmp'} == 1) {
			
			#These variables could be adjusted by locality or school district. We could also make them univesally 1, since most public schools offer free lunch and breakfast to all students, even pre-COVID.
			
			#Note that the CEP variable is one way in this code that students can get free meals. Individually within the breakfast and lunch codes below, we have also built in COVID legislation that also confers free breakfast and lunch to students.
			
			$elem_cep_lunch = $cep_takeup; # CEP is an input that will be defaulted to 0 but which users have the option to change to 1 if they select one of the free school meal programs and if the policy variables in the db indicate that the area where they live includes schools taking up the CEP option to provide free meals to all students regardless of income. Conceivably this could be broken down by meal by child, since some schools provide participate in CEP for only one of the two meals and children may be attending different schools with different school lunch policies.
			$elem_cep_bkfst = $cep_takeup; 
			$ms_cep_lunch = $cep_takeup; 
			$ms_cep_bkfst = $cep_takeup; 
			$hs_cep_lunch = $cep_takeup; 
			$hs_cep_bkfst = $cep_takeup; 

		}		
		
		# CALCULATING FAMILY INCOME FOR SCHOOL AND SUMMER MEAL ELIGIBILITY:
		#We can also run the income test for free lunch eligibility at this point, since that will be true across all children.  Identical to SSI income determinations, but SSI assistance is included. Reportable Income (https://www.ssa.gov/OP_Home/cfr20/416/416-app-k.htm) includes earnings, SSI, cash assistance, child support, and any other money available to pay for children’s meals. SNAP value is not counted. 

		$schoolmeals_inc_m = $out->{'earnings'}/12 + $out->{'child_support_recd_m'} + $in->{'spousal_sup_ncp'}/12 + $out->{'gift_income_m'} + $out->{'ssi_recd_mnth'} + $out->{'tanf_recd_m'} +$in->{'other_income_m'} + $in->{'selfemployed_netprofit_total'}/12 +  $in->{'unearn_gross_mon_inc_amt_ag'} + $out->{'ui_recd_m'} + $out->{'fli_plus_tdi_recd'}; # Note: Nowhere in the Federal Register 3/20/19 definition of "income" for determining eligibility for school meals do the rules explicitly include payments that would have been included in a TANF cash assistance grant had a family member not been under sanctions. https://www.federalregister.gov/documents/2020/03/20/2020-05982/child-nutrition-programs-income-eligibility-guidelines#:~:text=In%20accordance%20with%20the%20Department's,%2C%20charitable%20contributions%2C%20and%20bonds. 
		
		$schoolmeals_inc = $schoolmeals_inc_m *12;

		#CALCULATE FOR EACH CHILD:
		# Calculate per meal costs for each child according to age, divided by the number of weeks in a month, further divided by the number of meals per week (7 days per week * 3 meals per day).

		# Use food cost table to find value for child#foodcost_m based on child age:

		for (my $i = 1; $i <= 5; $i++) {

			# Use food cost table to find value for child#foodcost_m based on child age:
			my $sql = "SELECT cost FROM FRS_Food WHERE year = ? && age_min <= ? && age_max >= ?";
			if ($in->{'child'.$i.'_age'} != -1) { 
				my $stmt = $dbh->prepare($sql) || &fatalError("Unable to prepare $sql: $DBI::errstr");
				$stmt->execute($in->{"year"}, $in->{"child".$i."_age"}, $in->{"child".$i."_age"});
				${"child".$i."_foodcost_m"} = $stmt->fetchrow();
			} else {
				${"child".$i."_foodcost_m"} = 0; #SH note 11/1/19: There seemed to be an arbitarily high number here from 2017 (it equaled 3410), but as far as I can tell that error had no effect on the output of this code, since food reductions calculated here are only for children who are of certain ages, and this calculation is for the food costs of nonexistant children (meaning children whose ages are -1).
			}

			$permealcost = (${'child'.$i.'_foodcost_m'}/4.33)/(7*3);
			${'debug'.$i} = $permealcost;


			#Calculate meal prices for school breakfasts and lunches.

			# Check eligibility for national school breakfast program for all children. Students attending schools or districts participating in the Community Eligibility Provision (CEP) receive both school breakfasts and school lunches for free regardless of income. All Pittsburgh schools participate in this program, but in other locations (such as Kentucky or perhaps elsewhere in PA), only some schools participate, meaning that we will need formulas for both school and breakfast meals based on how much schools charge for both the full cost of meals and the reduced-price cost of meals (both of which are determined by school). In these locations, students are eligible for free lunches if their family's incomes are below 130% FPG or if they receive SNAP or TANF. They are eligible for reduced-price meals if their incomes are below 185% FPG.


			# SCHOOL BREAKFAST

			if ($in->{'nsbp'}==1 && $in->{'child'.$i.'_age'} >= 5) { 
				if($in->{'child'.$i.'_age'} < 11) {
					$bkfst_red_price = $elem_bkfst_red;
					$bkfst_paid_price = $elem_bkfst_paid;
					$cep_participation_bkfst = $elem_cep_bkfst;
				} elsif ($in->{'child'.$i.'_age'} < 15) {
					$bkfst_red_price = $ms_bkfst_red;
					$bkfst_paid_price = $ms_bkfst_paid;
					$cep_participation_bkfst = $ms_cep_bkfst;
				} elsif ($in->{'child'.$i.'_age'} < 18) {
					$bkfst_red_price = $hs_bkfst_red;
					$bkfst_paid_price = $hs_bkfst_paid;
					$cep_participation_bkfst = $hs_cep_bkfst;
				}
				
				# Now we use the above school, school district, and parent choice variable to determine reductions in school breakfasts:
				
				#These first three if-condtions check to see if any of the ways that meals are free are satisified here. This could be a very large OR statement but we are separating it out for simplicity.
				if($cep_participation_bkfst == 1 || $in->{'covid_sfsp_sso_expansion'} == 1) {
					${'child'.$i.'_bkfst_red'} = $schooldays * $permealcost;
				} elsif (($out->{'tanf_recd'}>0 || $out->{'fsp_recd'}>0 || $in->{'child'.$i.'_foster_status'} >= 1) || $schoolmeals_inc < $in->{'fpl'}*1.3) {
					${'child'.$i.'_bkfst_red'} = $schooldays * $permealcost;
				} elsif ($schoolmeals_inc <$in->{'fpl'}*1.85) {
					${'child'.$i.'_bkfst_red'} = $schooldays * &pos_sub($permealcost,$bkfst_red_price);
				} else {
					${'child'.$i.'_bkfst_red'} = $schooldays * &pos_sub($permealcost,$bkfst_paid_price);
				}
			} else {
				${'child'.$i.'_bkfst_red'} = 0;
			}

			# SCHOOL LUNCH
			# Similarly, we check for eligigibility for free or reduced-price lunch, which works exactly the same as breakfast above, but with different pricing. 

			if (($in->{'frpl'}==1 && $in->{'child'.$i.'_age'} >= 5) || ($in->{'prek'} == 1 && $in->{'child'.$i.'_age'} >= $out->{'prek_age_min'} && $in->{'child'.$i.'_age'} <= $out->{'prek_age_max'})) {  
				if($in->{'child'.$i.'_age'} < 11) {
					$lunch_red_price = $elem_lunch_red;
					$lunch_paid_price = $elem_lunch_paid;
					$cep_participation_lunch = $elem_cep_lunch;
				} elsif ($in->{'child'.$i.'_age'} < 15) {
					$lunch_red_price = $ms_lunch_red;
					$lunch_paid_price = $ms_lunch_paid;
					$cep_participation_lunch = $ms_cep_lunch;
				} elsif ($in->{'child'.$i.'_age'} < 18) {
					$lunch_red_price = $hs_lunch_red;
					$lunch_paid_price = $hs_lunch_paid;
					$cep_participation_lunch = $hs_cep_lunch;
				}

				if ($in->{'frpl'} == 1 && ($cep_participation_lunch == 1 || $in->{'covid_sfsp_sso_expansion'} == 1)) {
					${'child'.$i.'_lunch_red'} = $schooldays * $permealcost;
				} elsif ($in->{'prek'} == 1 && $in->{'child'.$i.'_age'} >= $out->{'prek_age_min'} && $in->{'child'.$i.'_age'} <= $out->{'prek_age_max'}) {
					#All children in PA's Pre-K program receive 1 free school meal, presumably through CACFP. Generating that savings, but not breakfast.
					${'child'.$i.'_lunch_red'} = $schooldays * $permealcost;
				} elsif (($out->{'tanf_recd'}>0 || $out->{'fsp_recd'}>0  || $in->{'child'.$i.'_foster_status'} >= 1) || $schoolmeals_inc < $in->{'fpl'}*1.3) {
					${'child'.$i.'_lunch_red'} = $schooldays * $permealcost;
				} elsif ($schoolmeals_inc <$in->{'fpl'}*1.85) {
					${'child'.$i.'_lunch_red'} = $schooldays * &pos_sub($permealcost,$lunch_red_price);
				} else {
					${'child'.$i.'_lunch_red'} = $schooldays * &pos_sub($permealcost,$lunch_paid_price);
				}
			} else {
				${'child'.$i.'_lunch_red'} = 0;
			}

			# AFTERSCHOOL SNACK/SUPPER
			# If a family has enrolled their child in an afterschool program that is participating in the federal CACFP program, they also get a free snack or supper. We are defaulting to supper here but can change that later on. For states where we are modeling the impact of public afterschool programs, we will be able to demonstrate the savings to families generated by this program separate from afterschol.
			#if ($out->{'afterschool_child'.$i} == 1 && $in->{'cacfp'} == 1 && (($in->{'prek'} == 1 && ($in->{'child'.$i.'_age'}==3 || $in->{'child'.$i.'_age'}==4))|| $in->{'child'.$i.'_age'} >= 5)) { 

			#	${'child'.$i.'_supper_recd'}  = $schooldays*$permealcost; 
			#}

			# SUMMER 
			# All children are eligible for free summer meals through the federal Summer Food Service Program (SFSP), but we model the reduction for only children over 2 years because usually done breastfeeding and usually cannot feed themselves before this age. The input variable we used fro DC was 'fsmp' because that was what the program was called locally, but it has been updated to the federal acronym in the 2019 code.
			# Because of the name of DC's program when we coded this in 2017, we are using the variable "fsmp" here. Eventually we should change this to use "sfsp" to correspond to the federal name for the program.
			
			#COVID NOTE: We incorporate the summer Pandemic-EBT program here, which provides $375/month during summers when the COVID public health emergency is occuring, in lieu of free meals available to children during the summer at school sites, because the USDA is deeming school sites as closed during the summer. See https://www.insidernj.com/press-release/nj-human-services-deliver-140m-summer-food-assistance-benefits-eligible-children/ and https://fns-prod.azureedge.net/sites/default/files/resource-files/2021-pandemic-ebt-summer-qas.pdf. 
			
			if ($in->{'covid_sfsp_sso_expansion'} == 1 && $in->{'child'.$i.'_age'} >= 0) {
				${'child'.$i.'_sfsp_red'} = $summer_pebt_amt;
			} else {
				if ($in->{'fsmp'} == 0 || $in->{'child'.$i.'_age'}<=2) { 
					${'child'.$i.'_sfsp_red'} = 0; 
				} else {
					${'child'.$i.'_sfsp_red'} = $summerdays * $permealcost; #This will zero out in towns where there is no free summer meal program. We use this input name even though the federel program is called "SFSP," as this was the local name for the program in DC in 2017, when we introduced this variable. A cleanup of the code could convert this input and all uses of it to "sfsp".
					#This is inclusive of teh COVID expansion of this program, which essentially extends it into the school year regardless of whether meals are provided onsite.
				}
			}
			
			# TOTALING UP MEAL REDUCTIONS FOR THE CHILD
			${'child'.$i.'_foodcost_red'} = &round(${'child'.$i.'_bkfst_red'} + ${'child'.$i.'_lunch_red'} + ${'child'.$i.'_supper_recd'} + ${'child'.$i.'_sfsp_red'});

			#ADDING IN THE SFSP/SSO COVID EXPANSION TO PROVIDE FREE BREAKFAST AND SUMMER TO ALL CHILDREN, REGARDLESS OF AGE.
			if ($in->{'covid_sfsp_sso_expansion'} == 1 && 1==0) { #This is a model of free meal provision if adopted universally.  So we're limiting the use of the extended free meal eligibiltiy to just modeling the provision of free meals to all students. We use a nonsensical condition here (1=0) to make sure this code is not active right now, but could be turned on in jurisdictions with univeral free meal programs available to all children. 
				if ($in->{'fsmp'} == 1) {
					#This program simply provides meals to all children who need it. It covers breakfast and lunch. Afterschool snacks are allowed, but for simplicity's sake, we are limiting our model of thesse meals to breakfast and lunch. Schools have flexibility for whether they are participating in this program via the various school nutrition programs. 
					#We still check for the fsmp flag (called "SFSP" in the list of benefits) because these meals are distributed at SFSP sites.
					#This calculation will supersede the previous calculations by simply covering the full cost of breakfast and lunch.
					#Administratively, this is done through SFSP/SSO, but federal waivers allowed for flexibiltiy to convert school nutrition programs to SFSP funding. So, it is reasonable to assume that a user will not necesssarily now which among these programs they are receiving meals from.
					${'child'.$i.'_foodcost_red'} = $permealcost *2 * 365;
				} else {
					#If the user has not clicked on free summer meals, we check for free or reduced price lunch or breakfast, and assume they can get free lunch or breakfast that way. We first reset the variable for the food cost reduction. We do this for every day of the year.
					${'child'.$i.'_foodcost_red'} = 0;
					if ($in->{'frpl'}==1) {
						${'child'.$i.'_foodcost_red'} = $permealcost * 365;
					}
					if ($in->{'nsbp'}==1) {
						${'child'.$i.'_foodcost_red'} += $permealcost *365;
					}
				}
			}

			#END OF PER-CHILD CALCULATION
		}

		$child_foodcost_red_total = $child1_foodcost_red + $child2_foodcost_red + $child3_foodcost_red + $child4_foodcost_red + $child5_foodcost_red; 
	}
	
	# outputs
	foreach my $name (qw(child_foodcost_red_total permealcost child1_foodcost_red child2_foodcost_red child3_foodcost_red child4_foodcost_red child5_foodcost_red)) {
		$out->{$name} = ${$name};
		$self->saveDebugValues("schoolsummermeals", $name, ${$name});
	}
	#debugs
	foreach my $variable (qw(child_foodcost_red_total child1_lunch_red child1_bkfst_red cep_participation_lunch child2_foodcost_m schoolmeals_inc_m schoolmeals_inc debug2 child1_sfsp_red)) {
		$self->saveDebugValues("schoolsummermeals", $variable, $$variable, 1);
	}

	return(0);
}

1;